### PR TITLE
Auth pages

### PR DESCRIPTION
**Pull request by Shivani-1524**
Added Login and Signup pages. When user clicks on the profile icon it by default leads to the login page.

### CODE REVIEW

**Review by mmanjuprasad — APPROVED** [review]
The UI looks good with autofill options.
In the login page u can remove the +6 character background text.

No changes required in code it is written well
you can merge the PR

**Review by gauravsinhaweb — APPROVED** [review]
Landing page looks so good, I hope the text 'Experience Gaming.
On a Whole New Level.' is temporary' because it doesn't make any sense for an ecom website.  Good to merge.

**Comment by Shivani-1524** [comment]
> Landing page looks so good, I hope the text 'Experience Gaming. On a Whole New Level.' is temporary' because it doesn't make any sense for an ecom website. Good to merge.

i meant experience as in the merch and the whole gaming setup that you can shop at the site but i get that it dosent make much sense. will try to come up with something better. Thanks a lot Gaurav!

**Comment by Shivani-1524** [comment]
> mmanjuprasad
okay 😀 thanks a lot!

**Pull request merged**
